meta:
  schema-version: 0.1.0
  created-on: "2024-09-03T11:29:47Z"
  cli-version: 0.2.0
projects:
  itamartestgts:
    targets:
      - package.json
    manager:
      ecosystem: node
      name: npm
      version: "7"
    overrides:
      semver:
        5.7.1:
          use: 5.7.1-sp1
        6.3.0:
          use: 6.3.0-sp1
        7.3.7:
          use: 7.3.7-sp1
      got:
        9.6.0:
          use: 9.6.0-sp1
      braces:
        3.0.2:
          use: 3.0.2-sp1
      word-wrap:
        1.2.3:
          use: 1.2.3-sp1
      http-cache-semantics:
        4.1.0:
          use: 4.1.0-sp1
      micromatch:
        4.0.5:
          use: 4.0.5-sp1
      json5:
        2.2.1:
          use: 2.2.1-sp1
